### ISSUE TITLE
in config/dev.exs, change lib/my_app_web to lib/app_web

### ISSUE THREAD

**Issue by jmarca** [carleryd/elm-hipster-stack#10]
https://github.com/carleryd/elm-hipster-stack/blob/faf63e00b7a53664f42dbfbf1d58dbc21a795332/config/dev.exs#L24-L25

Seems like cruft left over from the earlier shift from my_app to app

**Comment by carleryd** [comment]
I finally merged the PR to fix this so it should be resolved!
