### ISSUE TITLE
Build error (elm)

### ISSUE THREAD

**Issue by kosir** [carleryd/elm-hipster-stack#2]
Hi, I'm trying to run this code on cloud 9, so I'm using port 8081 (there are only 8080,8081 and 8082 ports available on cloud9, I think) and I get this build error on elm:

[info] Running App.Endpoint with Cowboy using http on port 8081
 50% 2/3 build modules-- SYNTAX PROBLEM --------- elm-stuff/packages/elm-lang/core/3.0.0/src/Array.elm

I ran into something unexpected when parsing your code!

2|     ( Array
       ^
I am looking for one of the following things:

```
something like `exposing (..)` which replaced `where` in 0.17
whitespace
```

Hash: 20f8fd16cff3c8d839e9  
Version: webpack 1.13.0
Time: 1291ms
 Asset     Size  Chunks             Chunk Names
app.js  1.89 kB       0  [emitted]  app
   [0] multi app 28 bytes {0} [built]
    + 2 hidden modules

ERROR in ./web/static/js/elm/src/Main.elm
Module build failed: 
 @ ./web/static/js/app.js 3:12-41

Do you have any experience what could be a reason for this error?
Thanks in andvance for any reply!

**Comment by kosir** [comment]
oh, sorry I missed syntax change in elm 0.17:
https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.17.md

**Comment by carleryd** [comment]
Yeah, for now you have to run the project with Elm 0.16. The project may be upgraded to support 0.17 in the coming weeks :)

**Comment by proProbe** [comment]
As you have noticed, the syntax error is caused by the new update in elm to 0.17. Migrating over to 0.17 may come in the future :D

**Comment by kosir** [comment]
Thanks, any hint how to downgrade elm?

**Comment by carleryd** [comment]
Maybe look into using this https://github.com/sonnym/elmenv I started using Elm in 0.16 so have never has this problem. If you want you are more than welcome to upgrade the project to 0.17 and do a PR 🎆

**Comment by kosir** [comment]
Thanks :) 
For now I'll just 
npm uninstall -g elm 
npm install -g elm@0.16

(It's builded successfully, great!)
