### ISSUE TITLE
Run on another port (problem, not issue)

### ISSUE THREAD

**Issue by kosir** [carleryd/elm-hipster-stack#3]
Hi, I know it's not a help forum, but have this problem:
I'm running elm-hipster stack on cloud9 (just testing stuff) on port 8081.
It's loaded really fast and looks great, but records doesn't get saved.
I changed port only in config/dev.exs.
Maybe I should change also somewhere else, but I don't know where.
Any hint what am I doing wrong?

This is my search:
Searching for 4000 in/elm_hipster whole word (Found 20 matches in 16 files)

**/elm_hipster/README.md:**
16:   Create new database by going to `localhost:4000/reset`
17:   Elm app now running on `localhost:4000`
20: Explore the database with GraphiQL at `localhost:4000/graphql`
**/elm_hipster/deps/phoenix/CHANGELOG.md:**
339:             url: "ws://localhost:4000",
**/elm_hipster/deps/phoenix/lib/phoenix/endpoint.ex:**
152:           [url: "ws://localhost:4000",
**/elm_hipster/deps/phoenix/lib/phoenix/endpoint/server.ex:**
17:       config   = default(config, otp_app, 4000)
**/elm_hipster/deps/phoenix_live_reload/lib/phoenix_live_reload/live_reloader.ex:**
38:        url: "ws://localhost:4000",
**/elm_hipster/deps/plug/README.md:**
41: Access "http://localhost:4000/" and we are done!
**/elm_hipster/deps/plug/lib/plug/adapters/cowboy.ex:**
11:     Defaults to 4000 (http) and 4040 (https).
122:   @http_cowboy_options  [port: 4000]
**/elm_hipster/deps/plug_graphql/README.md:**
94:   5. Open your browser to `http://localhost:4000/api?query={greeting}` and you should see something like this:
**/elm_hipster/node_modules/enhanced-resolve/lib/node.js:**
48: var asyncFileSystem = new CachedInputFileSystem(new NodeJsInputFileSystem(), 4000);
49: var syncFileSystem = new CachedInputFileSystem(new SyncNodeJsInputFileSystem(), 4000);
**/elm_hipster/node_modules/lodash/index.js:**
11653:      \* // => 4000
**/elm_hipster/node_modules/lodash/math/floor.js:**
21:  \* // => 4000
**/elm_hipster/priv/static/js/app.js:**
11272:     var url = "http://localhost:4000/graphql";
**/elm_hipster/web/static/js/elm/graphql-make:**
5: $make src/GraphQL/Ahead.graphql "http://localhost:4000/graphql"
**/elm_hipster/web/static/js/elm/index.html:**
12367:    var url = "http://localhost:4000/graphql";
**/elm_hipster/web/static/js/elm/elm-stuff/build-artifacts/0.16.0/user/project/1.0.0/GraphQL-Ahead.elmo:**
53:    var url = "http://localhost:4000/graphql";
**/elm_hipster/web/static/js/elm/src/GraphQL/Ahead.elm:**
14:     "http://localhost:4000/graphql"
Found 20 matches in 16 files

**Comment by carleryd** [comment]
Are you creating links without them being saved to the database? Because if so, mutations are not implemented, because they do not exist in elm-graphql https://github.com/jahewson/elm-graphql

**Comment by kosir** [comment]
a-ha! Thanks!

**Comment by carleryd** [comment]
This should definitely have been in the README, so I added it now :P
